model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128

checkpoint_path: "/content/drive/MyDrive/285/PyTorch-VAE/last.ckpt"


data_params:
  data_path: "/content/chest_xray_data/chest_xray"
  train_batch_size: 64
  val_batch_size:  64
  test_batch_size:  64
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265
  log_dir: logs/vae_training

trainer_params:
  accelerator: 'auto'
  devices: 1
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  
